/*
    Purpose:
    --------
    Performs magnitude analysis by measuring the size and distribution of
    key business entities such as customers, products, revenue, and sales.
    The queries summarize business performance across different dimensions,
    including country, gender, product category, and individual customers.
*/

-- Count customers by country to compare the size of each market.
SELECT
    country,
    COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Count customers by gender.
SELECT
    gender,
    COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Count the number of products within each category.
SELECT
    category,
    COUNT(DISTINCT product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Calculate the average product cost for each category.
SELECT
    category,
    COUNT(DISTINCT product_id) AS total_products,
    AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Calculate total revenue generated by each product category.
SELECT
    p.category,
    COUNT(DISTINCT product_id) AS total_products,
    SUM(sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
    ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_products DESC;

-- Calculate the lifetime revenue generated by each customer.
SELECT
    customer_id,
    c.first_name,
    c.last_name,
    SUM(sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY
    customer_id,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Summarize the quantity of items sold in each customer country.
SELECT
    c.country,
    SUM(quantity) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
    ON s.product_key = p.product_key
LEFT JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
